import { NextFunction, Request, Response } from "express";
import { ErrorCodes, HttpException } from "../exceptions/root";
import { InternalException } from "../exceptions/internal-exception";

export const errorHandler = (method: Function) => {
    return async (req: Request, res: Response, next: NextFunction) => {
        try {
            await method(req, res, next)
        } catch (error: any) {
            let exception : HttpException;
            if (error instanceof HttpException) {
                exception = error
            } else {
                exception = new InternalException("Internal server error" ,ErrorCodes.INTERNAL_EXCEPTION,  error?.message || error);                
            }
            next(exception);
        }
    }
}